name: ci-golang-workflow
on:
  push:
    branches:
      - feature/github-actions
  pull_request:
    branches:
      - master
jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: 1.20
      - run: go run cmd/main.go
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: adsons/crawler-fi-ms:latest